version: '3'

services:
  database:
    container_name: LiveCodeLabLuby
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER=LiveCodeLabLuby
      - MYSQL_PASSWORD=docker
      - MYSQL_DATABASE=LiveCodeLabLubyDB
      - TZ=America/Sao_Paulo
    command: --default-authentication-plugin=mysql_native_password
