service: serverlessmodulo2labluby
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /hello
          method: get

  world:
    handler: handler.world
    events:
      - httpApi:
          path: /world
          method: get

  post:
    handler: handler.post
    events:
      - httpApi:
          path: /post
          method: post

plugins:
  - serverless-plugin-typescript
