version: '3'

services:
  zookeeper:
    container_name: ZookeeperProvaLubyCashLabLubyApi
    image: wurstmeister/zookeeper:latest
    ports:
      - 2181:2181

  kafka:
    container_name: KafkaProvaLubyCashLabLubyApi
    image: wurstmeister/kafka:2.11-1.1.0
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "MSPApi:1:1, MSCApi:1:1, MSPService:1:1, MSCService:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  databaseapi:
    container_name: DatabaseProvaLubyCashLabLubyApi
    image: postgres
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=ProvaLubyCashLabLubyApi
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=ProvaLubyCashLabLubyApiDB
