version: '3'

services:
  zookeeper:
    container_name: ZookeeperContainer
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  kafka:
    container_name: KafkaContainer
    image: wurstmeister/kafka:2.11-1.1.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "MicroServiceEmail:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  database:
    container_name: DatabaseContainer
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=ProvaAdonisV5LabLuby
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=ProvaAdonisV5LabLubyDB
